
services:
  backend:
    build: ./backend
    container_name: project-root-backend
    command: python manage.py runserver 0.0.0.0:8000

    volumes:
      - ./backend:/app
    ports:
      - "8001:8000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: project-root-db
    environment:
      MYSQL_DATABASE: speedometer_db
      MYSQL_ROOT_PASSWORD: Hi@180103
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  frontend:
    build: ./frontend
    container_name: project-root-frontend
    ports:
      - "3001:3000"
